// Auto-generated by: supabase gen types typescript --local > src/types/supabase.ts
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      puzzles: {
        Row: {
          id: string;
          fen: string;
          moves: string[];
          source: string;
          lichess_id: string | null;
          rating: number | null;
          popularity: number | null;
          themes: string[] | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["puzzles"]["Row"], "id" | "created_at"> & { id?: string; created_at?: string };
        Update: Partial<Database["public"]["Tables"]["puzzles"]["Insert"]>;
      };
      puzzle_sets: {
        Row: { id: string; user_id: string; name: string; description: string | null; created_at: string };
        Insert: Omit<Database["public"]["Tables"]["puzzle_sets"]["Row"], "id" | "created_at"> & { id?: string; created_at?: string };
        Update: Partial<Database["public"]["Tables"]["puzzle_sets"]["Insert"]>;
      };
      puzzle_set_puzzles: {
        Row: { puzzle_set_id: string; puzzle_id: string; added_at: string };
        Insert: Omit<Database["public"]["Tables"]["puzzle_set_puzzles"]["Row"], "added_at"> & { added_at?: string };
        Update: Partial<Database["public"]["Tables"]["puzzle_set_puzzles"]["Insert"]>;
      };
      training_sessions: {
        Row: { id: string; user_id: string; puzzle_set_id: string; cycle_number: number; started_at: string; completed_at: string | null; queue_state: Json };
        Insert: Omit<Database["public"]["Tables"]["training_sessions"]["Row"], "id" | "started_at"> & { id?: string; started_at?: string };
        Update: Partial<Database["public"]["Tables"]["training_sessions"]["Insert"]>;
      };
      puzzle_attempts: {
        Row: { id: string; session_id: string; puzzle_id: string; user_id: string; solved_correctly: boolean; time_taken_ms: number | null; attempt_number: number; created_at: string };
        Insert: Omit<Database["public"]["Tables"]["puzzle_attempts"]["Row"], "id" | "created_at" | "attempt_number"> & { id?: string; created_at?: string; attempt_number?: number };
        Update: Partial<Database["public"]["Tables"]["puzzle_attempts"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
